[project]
name = "langgraph-introduction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-openai>=0.3.28",
    "langgraph>=0.6.3",
]
